@startuml


database GitHubLab [
<b>GitHub Lab</b> repos
----
Includes examples
and other artefacts
]

database GitHubHDR [
<b>GitHub HDR</b> repos
----
Includes examples
and other artefacts
]

database GitHubPs [
<b>GitHub PS</b> repos
----
Includes examples
and other artefacts
]

database GitHubXph [
<b>GitHub XpanDH</b>
----

]

collections PatientSummaryIg [
Patient Summary examples (IG)
]

collections PatientSummary [
Patient Summary examples (other)
]

collections LabReportIg [
Lab Rpt examples (IG)
]

collections LabReport [
Lab Rpt examples (other)
]

collections HDRIg [
HDR examples (IG)
]

collections HDR [
HDR examples (other)
]


artifact "This guide"
artifact "Laboratory Report IG"
artifact "Hospital Discharge Report IG"
artifact "Patient Summary IG"


"This guide" -- GitHubXph 
"This guide" o-- "Laboratory Report IG"
"This guide" o-- "Hospital Discharge Report IG"
"This guide" o-- "Patient Summary IG"


"Patient Summary IG" -- GitHubPs 
"Patient Summary IG" *-- PatientSummaryIg 
GitHubPs -- PatientSummary 
GitHubPs -- PatientSummaryIg

"Laboratory Report IG" -- GitHubLab 
"Laboratory Report IG" *-- LabReportIg 
GitHubLab -- LabReport 
GitHubLab -- LabReportIg

"Hospital Discharge Report IG" -- GitHubHDR
"Hospital Discharge Report IG" *-- HDRIg
GitHubHDR -- HDR
GitHubHDR -- HDRIg


@enduml